RTX support
jellyfish-dev/membrane_webrtc_plugin pull request #94
Opened 2022-08-02 13:58 UTC by bblaszkow06

2023-01-09 18:36 UTC, mickel8 requested changes
TBC

It looks muuuch more better than it was previously but understanding all changes takes some time

2023-01-09 18:36 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    state = %State{state | tracks: TracksState.register_stream(state.tracks, ssrc, track_info)}
Actually we could even entirely get rid of `add_inbound_tracks` and when a new SDP offer arrives we could just call update on TracksState as it would update internal maps.

Or we should use update only for already existing tracks and add_inbound_tracks for new tracks. Calling update for all tracks and then adding new tracks once again isn't intuitive (lines 574-577)

2023-01-09 18:36 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    state = %State{state | tracks: TracksState.register_stream(state.tracks, ssrc, track_info)}
One more advantage is that we could remove `:unicast` `:simulcast` from `stream_info` type

2023-01-09 18:36 UTC, mickel8 commented on lib/membrane_webrtc_plugin/track.ex
> +                selected_encoding_key: nil,
Could we rename it to `codec`? Or maybe we could change `name: String.t()` in `Track.Encoding` to `codec: codec()` where `codec() :: :OPUS | :H264 | :VP8 | etc.`

2023-01-11 10:56 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +           depayloading_filter :: module()}
It's not so easy:
1. In the case of simulcast, rid & ssrc will be part of a list in a track, so it would have to be separate anyway
2. There's no place for depayloading_filter inside Track struct

So I'd consider creating a new struct for this whole message or leaving it as-is.

2023-01-11 11:02 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/extension/repaired_rid.ex
> +  # for the whole session mid for same buffer will be the same.
It's a leftover from copy-paste from `Extension.Rid` :stuck_out_tongue: with git blame leading to @Rados13 
Moreover, that seems to be a copy-paste from `Extension.Mid` :upside_down_face:
I guess both comments can be removed

2023-01-11 12:46 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/endpoint_bin/tracks_state.ex
> +    |> Map.replace!(:used_ssrcs, MapSet.put(state.used_ssrcs, ssrc))
MapSet and struct don't implement Access behaviour, so I cannot use ssrc as a key in `put_in` and `put_in` with `:used_ssrcs` would look like below, which is IMO quite ugly and might be slower

```suggestion
    state
    |> put_in([Access.key!(:used_ssrcs)], MapSet.put(state.used_ssrcs, ssrc))
```

2023-01-11 12:52 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/endpoint_bin/tracks_state.ex
> +      |> Map.new(&{&1.id, &1})
Because the default value for `tracks_kw[:inbound]` is `nil` and `Map.new` would raise.

2023-01-11 13:35 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/endpoint_bin/tracks_state.ex
> +        nil
I'm not a fan of implicit returns - maybe we could ask for a third opinion?

2023-01-12 13:14 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track.ex
> +                selected_encoding_key: nil,
The main issue here is with the transition from `Engine.Track` to `WebRTC.Track` - Engine keeps an atom (e.g. `:OPUS`) that is put inside WebRTC.Track, but the `Track.Encoding` struct is taken from the SDP offer after parsing based on that atom. This means we'd have to generate an empty `Encoding` struct with only the name.

In general, the way the `Track`s are passed around in rtc engine could be revisited and possibly simplified but IMO it's outside of the scope of this PR

2023-01-13 09:50 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +           depayloading_filter :: module()}
Let's keep the current solution

2023-01-13 10:27 UTC, mickel8 commented on lib/membrane_webrtc_plugin/endpoint_bin/tracks_state.ex
> +        nil
Nah, we can keep it

2023-01-13 10:44 UTC, mickel8 commented on lib/membrane_webrtc_plugin/track.ex
> +                selected_encoding_key: nil,
Ok but I would still rename `selected_encoding_key` to `codec`

2023-01-13 13:22 UTC, mickel8 requested changes

2023-01-20 11:33 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/endpoint_bin/tracks_state.ex
> +          used_ssrcs: MapSet.t(RTP.ssrc_t()),
You'd also have to include ssrcs from `state.outbound`. That's a bit of optimization and I was tempted to include it when it turned out generate_ssrcs happens to update it and I didn't want to discard it. Plus, it seems way easier to maintain that set with TracksState extracted.

BTW, there was a bug before as the set was created from `track.ssrc` which could be a list that was never flattened

2023-01-20 12:01 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track.ex
> +      {rtpmap, fmtps, rtx_fmtp, red_payload_type}
FMTP is defined as `Media Format Parameter` and this is a list of those, so IMO plural here is the best option

2023-01-20 14:28 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track/encoding.ex
> +          format_params: FMTP.t() | nil
Well, it would be easier to use it in these two functions, but harder anywhere outside.
* `payload_type` appears in the `m=` line, so it should stay at top-level as in theory `rtpmap` can be omitted for static payload types (although Chrome sends it anyway)
* for the same reason clock_rate is problematic
* `audio_channels` would loose it's interpretation (`rtp_mapping.params` is less readable)
* Flattening makes the calls getting the values shorter

The only change I'd make is to replace `rtx` map with `FMTP` struct (assuming it derives `Inspect` with `:optional` keys

2023-01-20 14:32 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track.ex
> +                selected_encoding_key: nil,
I don't really like both of these :man_shrugging: Codec and encoding mean more or less the same thing, the distinction between them wouldn't be clear to me.
Digging a bit in RFCs for SDP I came up with the idea of renaming `Encoding` struct to `Format` with `encoding_name` field. The `:selected_encoding_key` could become `:encoding` and would match the Engine option more closely.

2023-01-23 12:17 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/endpoint_bin.ex
> +    state = %State{state | tracks: TracksState.register_stream(state.tracks, ssrc, track_info)}
Extracted as https://membraneframework.atlassian.net/browse/RTC-106

2023-01-23 12:48 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track/encoding.ex
> +          format_params: FMTP.t() | nil
Leaving the idea for now, I've extracted the ticket for this idea: https://membraneframework.atlassian.net/browse/RTC-108

2023-01-23 14:02 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track.ex
> +                selected_encoding_key: nil,
To be continued in https://membraneframework.atlassian.net/browse/RTC-110

2023-01-23 14:07 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/track.ex
> +      {rtpmap, fmtps, rtx_fmtp, red_payload_type}
Turned out it depends on which RFC you refer to ¯\_(ツ)_/¯
You were right and in [RFC8866](https://www.rfc-editor.org/rfc/rfc8866#name-fmtp-format-parameters) it has that plural form, so I'll keep the key name in Track struct but rename that variable

2023-01-23 14:19 UTC, bblaszkow06 commented on lib/membrane_webrtc_plugin/sdp.ex
> +    encoding_name_to_find = Utils.encoding_name_to_string(track.selected_encoding_key)
This is the spot where `track` has only `:selected_encoding_key`, so I cannot use `track.selected_encoding`

2023-01-23 15:56 UTC, mickel8 approved these changes

2023-02-23 17:27 UTC, mickel8 approved these changes

2023-02-23 17:28 UTC, merged